name: Server

on:
  workflow_dispatch:
  schedule:
   - cron: '0 */6 * * *'
    
permissions:
  contents: read
  
env:
  MONGO_URI : ${{secrets.MONGO_URI}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
  

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '20'


    - name: Setup CF
      run: |
        ${{ secrets.CF_CONFIG }}


    - name: Install Dependencies
      run: npm install vite -g && npm install
      working-directory: ./server

    - name: Setup Deploy
      run: |
        NODE_ENV=production
        npm run dev
      #chmod +x ./run.sh && sudo ./run.sh
      # pm2 start server/app.js -i 4
      working-directory: ./server

 
